---
abstract: 'define new keywords in pure Perl'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Dir::Self: 0
  Test::More: 0
  strict: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Keyword-Simple
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::EndOfScope: 0
  Carp: 0
  XSLoader: 0
  perl: 5.012000
  warnings: 0
resources:
  repository: git://github.com/mauke/Keyword-Simple
version: 0.02
